name: route_task
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  google_fonts: 6.1.0
  dartz: ^0.10.1
  dio: ^5.4.2+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  injectable: ^2.4.0
  get_it: ^7.6.8
  freezed: ^2.5.2
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
